# Generated by Django 4.2.3 on 2026-06-18 20:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('simple_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('parentId', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='layer.geography')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('symbol', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layer.department')),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('long_description', models.CharField(blank=True, max_length=500, null=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, help_text='Describes the type sub-indicators', max_length=100, null=True)),
                ('type', models.CharField(blank=True, help_text='Defines the type of indicator that is Raw, Derived, etc.', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=1)),
                ('is_visible', models.BooleanField(blank=True, default=False)),
                ('IDS_dataSpace', models.URLField(blank=True, help_text='Dataset link from the indicators CSV column "IDS_dataSpace".', max_length=500, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layer.department')),
                ('geography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layer.geography')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_field', to='layer.indicators')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layer.scheme')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layer.unit')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layer.geography'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_period', models.CharField(blank=True, max_length=100, null=True)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layer.geography')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.indicators')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layer.scheme')),
            ],
            options={
                'indexes': [models.Index(fields=['geography', 'data_period'], name='layer_data_geograp_d3056f_idx')],
            },
        ),
    ]
