# Generated by Django 4.2.3 on 2026-07-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='department',
        ),
        migrations.RemoveField(
            model_name='data',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='department',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='scheme',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
    ]
