# Generated by Django 4.2.3 on 2026-04-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicators',
            old_name='ids_dataspace',
            new_name='IDS_dataSpace',
        ),
    ]
