# Generated by Django 4.2.3 on 2026-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_rename_ids_dataspace_indicators_ids_dataspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='IDS_dataSpace',
            field=models.URLField(blank=True, help_text='Dataset link from the data dictionary (CSV column "IDS_dataSpace", e.g. sheet dev_data_dictionary-assam).', max_length=500, null=True),
        ),
    ]
