# Generated by Django 4.2.3 on 2026-05-13 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0003_alter_indicators_ids_dataspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='simple_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='geography',
            name='type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='IDS_dataSpace',
            field=models.URLField(blank=True, help_text='Dataset link from the indicators CSV column "IDS_dataSpace".', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['geography', 'data_period'], name='layer_data_geograp_d3056f_idx'),
        ),
    ]
