# Generated by Django 6.0.6 on 2026-06-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0005_indicators_module_data_module_raster'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='data',
            new_name='layer_data_module_9a94f0_idx',
            old_name='layer_data_module_period_idx',
        ),
    ]
