# Generated by Django 4.2.3 on 2026-06-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0006_rename_layer_data_module_period_idx_layer_data_module_9a94f0_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='raster_file',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='is_raster_available',
        ),
    ]
