# Generated by Django 4.2.3 on 2026-06-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0007_remove_data_raster_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='is_raster_available',
            field=models.BooleanField(default=False, help_text='Whether a state-level raster layer exists for this indicator.'),
        ),
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_period', models.CharField(max_length=100)),
                ('filename', models.CharField(help_text='Raster filename under data/<module>/raster/<state>/.', max_length=500)),
                ('module', models.CharField(db_index=True, help_text="Hazard module (mirrors indicator.module), e.g. 'flood', 'heat'.", max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geography', models.ForeignKey(help_text='STATE geography that owns this raster.', on_delete=django.db.models.deletion.CASCADE, to='layer.geography')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.indicators')),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'data_period'], name='layer_raste_module_dd9c38_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rasterlayer',
            constraint=models.UniqueConstraint(fields=('indicator', 'geography', 'data_period', 'module'), name='layer_rasterlayer_unique_indicator_geo_period_module'),
        ),
    ]
