# Generated by Django 4.2.3 on 2026-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0008_raster_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='raster_file',
            field=models.CharField(blank=True, help_text='Raster filename under data/<module>/raster/<state>/, when applicable.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='is_raster_available',
            field=models.BooleanField(default=False, help_text='Whether a raster layer exists for this indicator.'),
        ),
        migrations.DeleteModel(
            name='RasterLayer',
        ),
    ]
