# Generated by Django 4.2.3 on 2026-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0009_data_raster_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='fetch_raster_from_state',
            field=models.BooleanField(default=False, help_text='When true, serve the state-level GeoTIFF clipped to the requested geography boundary instead of a per-geography file.'),
        ),
    ]
