# Generated by Django 4.2.3 on 2026-06-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer", "0010_fetch_raster_from_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicators",
            name="fetch_raster_from_state",
        ),
    ]
