# Generated by Django 4.2.3 on 2026-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0011_remove_indicators_fetch_raster_from_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='raster_min_dark',
            field=models.BooleanField(default=False, help_text='Raster colormap polarity from CSV rasterPolarity: when false (y), high values are red/dark; when true (n), low values are red/dark.'),
        ),
    ]
