# Generated by Django 4.2.3 on 2026-06-22 08:26

from django.db import migrations, models


def _copy_polarity(apps, schema_editor):
    Indicators = apps.get_model("layer", "Indicators")
    for row in Indicators.objects.all().only("id", "raster_min_dark"):
        # raster_min_dark True meant inverted (n); raster_polarity True means normal (y).
        row.raster_polarity = not row.raster_min_dark
        row.save(update_fields=["raster_polarity"])


class Migration(migrations.Migration):

    dependencies = [
        ("layer", "0012_indicators_raster_min_dark"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicators",
            name="raster_polarity",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "CSV rasterPolarity: True (y) = high values red/dark; "
                    "False (n) = low values red/dark."
                ),
            ),
        ),
        migrations.RunPython(_copy_polarity, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="indicators",
            name="raster_min_dark",
        ),
    ]
